### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by zainmehdi** [Namburger/edgetpu-detection-camera#2]
Hi,
Thanks for the package. I compiled it as mentioned in your docs but when I am running Edgetpu example its giving me the segmentation fault.

Error: Encountered unresolved custom op edgetpu-custom-op
Error: Node number 0 (edge-custom-op) failed to prepare
Platform : Raspberry Pi4
OS: Raspbian Buster

**Comment by Namburger** [comment]
Most likely an outdated version of libedgetpu, can you share the outputs of:
```
dpkg -l | grep libedgetpu
```

**Comment by zainmehdi** [comment]
It was version 14. I have uninstalled your package as of now but I can confirm it was 14. I also tried your minimal package and got the same error.

**Comment by Namburger** [comment]
Humn, what OS are you doing this on?
Can you try capturing the strace logs? I can probably find which share library was actually loaded during runtime :)

**Comment by zainmehdi** [comment]
Thanks and Sure , I will compile your minimal package again since it takes less time and come back to you. I am using raspbian buster on raspberry pi4

**Comment by zainmehdi** [comment]
Hi @Namburger here is the log file.  https://drive.google.com/file/d/1AEIk2MNh0ZhlfHzEXig0zCZpX1f3F4ts/view?usp=sharing

**Comment by Namburger** [comment]
@zainmehdi Humnnn, looks like you're right o_0, from the strace:
```
openat(AT_FDCWD, "/home/pi/edgetpu-minimal-example/libedgetpu/direct/armv7a/libedgetpu.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
```
Let me try to reproduce on my pi, haven't touch it in a while :)

**Comment by Namburger** [comment]
Humn, I can't reproduce it, unfortunately, just did a fresh installed of buster, and tried the minimal example:
```
strace ../out/armv7a/minimal ../test_data/mobilenet_v1_1.0_224_quant_edgetpu.tflite ../test_data/resized_cat.bmp ../test_data/imagenet_labels.txt 2> strace.txt
...
Class: Egyptian cat
Score: 0.792969
...
```
Even strace shows that I'm loading the same `.so` that I used in my repo...
```
cat strace.txt | grep libedgetpu.so
...
openat(AT_FDCWD, "/home/pi/workspace/edgetpu-minimal-example/libedgetpu/direct/armv7a/libedgetpu.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
```
Here is the md5sum:
```
md5sum /home/pi/workspace/edgetpu-minimal-example/libedgetpu/direct/armv7a/libedgetpu.so.1
4e8ca36b62492f87ff59591e36186569  /home/pi/workspace/edgetpu-minimal-example/libedgetpu/direct/armv7a/libedgetpu.so.1
```

I'm not so sure, could you try adding pi to plugdev group?
```
sudo usermod -aG plugdev pi
sudo reboot now
```

[Edit] FYI, just got this camera demo working also, these are both on a fresh installation of raspbian buster :/ 
Sorry, I'm not sure why you would have this problem, but `Error: Node number 0 (edge-custom-op) failed to prepare` is 100% due to mismatching `libtensorflow-lite` and `libedgetpu.so`. I would check the md5sum to make sure that you have the exact so file as above.

**Comment by zainmehdi** [comment]
@Namburger After adding plugdev I am able to run minimal example. Thanks alot. I am trying the camera example now. I will update here soon.

**Comment by zainmehdi** [comment]
I have checked the camera example as well and its working now. Thanks alot :). Can you please mention someway with which cmake wont compile tf opencv etc everytime I make some change in your src file. I think its downloading and compiling on every build.

**Comment by Namburger** [comment]
Awesome, have fun!
Oh I don't think cmake is recompiling each time, i believe it is just checking the source file of those libraries to see if there are any changes and then relinking everything. I have no idea how to beat that lol I definitely looked it up before haha
