### ISSUE TITLE
build fails on Ubuntu

### ISSUE THREAD

**Issue by usbguru** [Namburger/edgetpu-detection-camera#3]
looks like the script needs a separate version requirement for Ubuntu:
build$ cmake ..
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.11 or higher is required.  You are running version 3.10.2

$ sudo apt-get install cmake
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version (3.10.2-1ubuntu2.18.04.1).

**Comment by Namburger** [comment]
Ahh, if you install cmake using my provided script, it'll make sure it meets version requirements

Or you can just upgrade your cmake to meet the requirements

Or you can try lowering the requirements here: https://github.com/Namburger/edgetpu-detection-camera/blob/master/CMakeLists.txt#1 (but I haven't tested build on a lower cmake version yet)
