### ISSUE TITLE
Build failed on absl-gitupdate.cmake

### ISSUE THREAD

**Issue by ting3000** [Namburger/edgetpu-detection-camera#4]
Hi @Namburger I tried to build on the Coral Dev Board, and the make process failed with following error, could you please help. Thanks!

Scanning dependencies of target absl
[ 83%] Creating directories for 'absl'
[ 85%] Performing download step (git clone) for 'absl'
Cloning into 'absl'...
remote: Enumerating objects: 4315, done.        
remote: Counting objects: 100% (4315/4315), done.        
remote: Compressing objects: 100% (2221/2221), done.        
remote: Total 4315 (delta 2712), reused 3383 (delta 2070), pack-reused 0        
Receiving objects: 100% (4315/4315), 3.73 MiB | 2.38 MiB/s, done.
Resolving deltas: 100% (2712/2712), done.
Your branch is up to date with 'origin/master'.
Already on 'master'
[ 88%] Performing patch step for 'absl'
[ 90%] Performing update step for 'absl'

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'mendel@red-pig.(none)')
Cannot save the current index state
CMake Error at /home/mendel/sdcard/spacer/development/edgetpu-detection-camera/build/absl/tmp/absl-gitupdate.cmake:80 (message):
  Failed to stash changes

make[2]: *** [CMakeFiles/absl.dir/build.make:113: absl/src/absl-stamp/absl-update] Error 1
make[1]: *** [CMakeFiles/Makefile2:278: CMakeFiles/absl.dir/all] Error 2
make: *** [Makefile:101: all] Error 2

**Comment by Namburger** [comment]
Just run this lol
```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

**Comment by ting3000** [comment]
Thanks!
